# Workflow de integração contínua (CI) responsável por executar automaticamente
# os testes unitários da aplicação sempre que houver push na branch principal.
# A estrutura foi mantida simples e organizada para permitir futuras expansões.

# Nome exibido na aba Actions do GitHub
name: Continuous Integration

# Evento que dispara a execução do workflow
on:
  push:
    branches:
      - main   # Executa somente quando houver envio de código para a branch main

# Variáveis globais reutilizáveis em qualquer job do workflow
env:
  NODE_VERSION: '24'   # Define a versão padrão do Node.js utilizada no pipeline
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_PROJECT_ID:  ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}

jobs:
  # Job único responsável pela validação dos testes unitários
  unit-tests:
    name: Unit Tests   # Nome amigável exibido visualmente no GitHub Actions
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do código-fonte do repositório para dentro da máquina virtual
      - name: Checkout
        uses: actions/checkout@v6.0.2

      # Instala e configura a versão do Node.js definida na variável global NODE_VERSION
      - name: Setup Node
        uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Habilita o Corepack para que o Yarn seja gerenciado automaticamente
      # conforme a configuração do projeto e versão presente no lockfile
      - name: Enable Corepack
        run: corepack enable

      # Instala todas as dependências do projeto respeitando exatamente
      # o arquivo yarn.lock para garantir reprodutibilidade no ambiente CI
      - name: Install dependencies
        run: yarn install

      # Executa os testes unitários utilizando o script configurado no package.json
      # neste caso: "test": "vitest run"
      - name: Run unit tests
        run: yarn test
  
  build-and-deploy:
    name: Build & Deploy Vercel Preview
    needs: [unit-tests]
    runs-on: ubuntu-latest    

    steps:
      # 1. Faz o checkout do código-fonte do repositório para dentro da máquina virtual
      - name: Checkout
        uses: actions/checkout@v6.0.2

      # 2. Instala e configura a versão do Node.js definida na variável global NODE_VERSION
      - name: Setup Node
        uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      # 3. Habilita o Corepack para que o Yarn seja gerenciado automaticamente conforme a configuração do projeto e versão presente no lockfile
      - name: Enable Corepack
        run: corepack enable

      # 4. Instala todas as dependências do projeto respeitando exatamente o arquivo yarn.lock para garantir reprodutibilidade no ambiente CI
      - name: Install dependencies
        run: yarn install

      # 5. Build para o Vercel
      - name: Build Vercel
        run: yarn vercel build --token=$VERCEL_TOKEN

      # 6. Deploy preview para o Vercel
      - name: Deploy Vercel
        run: yarn vercel deploy --prebuilt --target=preview --token=$VERCEL_TOKEN --scope=$VERCEL_SCOPE 